# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
    - name: Conda info
      shell: pwsh
      run: conda info
        
    - name: Conda list
      shell: pwsh
      run: conda list
        
    - name: Install dependencies
      shell: pwsh 
      run: |
        conda update conda --upgrade conda
        conda install flake8 pytest
        conda install --yes --file requirements.txt
    - name: Fetch opencv_contrib
      shell: pwsh 
      run: |
        conda install -c conda-forge opencv
    - name: Lint with flake8
      shell: pwsh 
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: pwsh 
      run: |
        conda install pytest
        pytest
