# SPDX-FileCopyrightText: 2021 Louisa Marie Kienesberger <e11775781@student.tuwien.ac.at>
#
# SPDX-License-Identifier: BSD-3-Clause

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

#   runs-on: ubuntu-latest
    
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        
    - name: Conda info
      shell: pwsh
      run: conda info
        
    - name: Conda list
      shell: pwsh
      run: conda list
        
    - name: Install dependencies
      shell: pwsh 
      run: |
        conda update conda --upgrade conda
        conda update -c conda-forge --all
        conda install -c conda-forge flake8 pytest
        conda install -c conda-forge --yes --file requirements.txt
        
    - name: Installing needed packages
      shell: pwsh 
      run: |
        conda install -c conda-forge scipy numba opencv trackpy lmfit ipympl scikit-learn pyqt pytables
        
    - name: Lint with flake8
      shell: pwsh 
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: pwsh 
      run: |
        conda install pytest
        pytest
